#!/bin/sh

# Process staged files
git diff --cached --name-status | while read -r status file; do
  # Check if the file is a blog post
  if echo "$file" | grep -qE '^src/data/blog/.*\.(md|mdx)$'; then
    current_time=$(date -u "+%Y-%m-%dT%H:%M:%SZ")

    case "$status" in
      A)
        echo "Updating pubDatetime and modDatetime for new file: $file"
        # For new files, set both pubDatetime and modDatetime
        sed -i \
          -e "/---.*/,/---.*/s/^pubDatetime:.*$/pubDatetime: $current_time/" \
          -e "/---.*/,/---.*/s/^modDatetime:.*$/modDatetime: $current_time/" \
          "$file"
        git add "$file"
        ;;
      M)
        echo "Updating modDatetime for modified file: $file"
        # For modified files, only update modDatetime
        sed -i "/---.*/,/---.*/s/^modDatetime:.*$/modDatetime: $current_time/" "$file"
        git add "$file"
        ;;
    esac
  fi
done

pnpm run build
