#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get current time (UTC)
current_time=$(date -u "+%Y-%m-%dT%H:%M:%SZ")

git status --porcelain | while IFS= read -r line; do
  # Get the status (M, A, D, etc.) and file path
  status=$(echo "$line" | awk '{print $1}')
  file=$(echo "$line" | awk '{print $2}')
  
  # Check if the file is in the correct directory (src/data/blog)
  if [[ "$file" == src/data/blog/* ]]; then
    
    # Process only .md or .mdx files
    if [[ "$file" == *.md ]] || [[ "$file" == *.mdx ]]; then
      file_to_process="$file"

      # Ensure the file exists (it hasn't been deleted)
      if [ -f "$file_to_process" ]; then
        
        # Get current draft status
        is_draft=$(grep "^draft:" "$file_to_process" | sed 's/^draft: *//;s/ *$//')
        
        case "$status" in
          A|AM)
            # New file found
            echo "Updating modDatetime for new file: $file_to_process"
            sed -i '' "/---.*/,/---.*/s/^modDatetime:.*$/modDatetime: $current_time/" "$file_to_process"
            git add "$file_to_process"
            ;;
            
          M|MM)
            # Modified file
            
            # Check previous draft status from HEAD
            was_draft=$(git show HEAD:"$file" 2>/dev/null | grep "^draft:" | sed 's/^draft: *//;s/ *$//')
            
            if [ "$was_draft" == "true" ] && [ "$is_draft" == "false" ]; then
              echo "Publishing draft: $file_to_process"
              # Update pubDatetime and modDatetime
              sed -i '' "/---.*/,/---.*/s/^pubDatetime:.*$/pubDatetime: $current_time/" "$file_to_process"
              sed -i '' "/---.*/,/---.*/s/^modDatetime:.*$/modDatetime: $current_time/" "$file_to_process"
            else
              echo "Updating modDatetime for modified file: $file_to_process"
              # Only update modDatetime
              sed -i '' "/---.*/,/---.*/s/^modDatetime:.*$/modDatetime: $current_time/" "$file_to_process"
            fi
            
            git add "$file_to_process"
            ;;
        esac
      fi
    fi
  fi
done
